sleep1:
    type: SleepApplication
    sleep_time: 2.0
    num_requests: 2

sleep2:
    type: SleepApplication
    num_requests: 1

another1:
    type: AnotherApplication
    another_config: "custom_value"
    num_requests: 3

imagegen1:
    type: ImageGen
    num_requests: 3

deep_research1:
    type: DeepResearch
    num_requests: 1

chatbot1:
    type: Chatbot
    num_requests: 10

live_captions1:
    type: LiveCaptions
    num_requests: 1

workflows:
    first_sleep:
        uses: sleep1
    
    second_sleep:
        uses: sleep2
        depend_on: ["first_sleep"]
    
    another_task:
        uses: another1
        depend_on: ["first_sleep", "second_sleep"] 

    imagegen_task:
        uses: imagegen1
        depend_on: ["another_task"]

    deep_research_task:
        uses: deep_research1
        depend_on: ["another_task"]

    chatbot_task:
        uses: chatbot1
        depend_on: ["another_task"]

    live_captions_task:
        uses: live_captions1
        depend_on: ["another_task"]