lv:
    num_requests: 1
    device: cpu
    mps: 100
    client_command_file: datasets/whisper-earnings21/5-min-chunks/4320211_chunk_002.wav
    type: LiveCaptions

workflows:
    start_captions:
        uses: lv