imagegen1:
    model: /mnt/tmpfs/models/stable-diffusion-3.5-medium-turbo
    # server_model: CompVis/stable-diffusion-v1-4
    num_requests: 50
    device: cpu
    type: ImageGen
    mps: 100

workflows:
    generate_image:
        uses: imagegen1