chat1:
    model: /home/yilegu/ConsumerBench/models/Llama-3.2-1B/Llama-3.2-1B-Instruct-Q8_0.gguf
    num_requests: 30
    device: gpu
    type: Chatbot
    # mps: 33

workflows:
    chat_summary:
        uses: chat1 