chat1:
    model: /home/cc/models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    num_requests: 50
    device: gpu
    type: Chatbot
    # mps: 33

workflows:
    chat_summary:
        uses: chat1 