Literature Review (deep_research):
    server_model: models/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-f16.gguf
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 1
    device: gpu
    type: deep_research
    mps: 100

workflows:
    literature_review:
        uses: Literature Review (deep_research)
        background: true