chat1:
    model: /mnt/d/rohan/models/Llama-3.2-1B/Llama-3.2-1B-Instruct-f16.gguf
    num_requests: 10
    device: gpu
    type: Chatbot
    # mps: 33

workflows:
    chat_summary:
        uses: chat1 